//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public alumno()
        {
            this.det_asist = new HashSet<det_asist>();
            this.confirmacion = new HashSet<confirmacion>();
        }
    
        public int id_alumno { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string password { get; set; }
        public byte habilitado { get; set; }
    
        public virtual ICollection<det_asist> det_asist { get; set; }
        public virtual ICollection<confirmacion> confirmacion { get; set; }
    }
}
