//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public asistencia()
        {
            this.det_asist = new HashSet<det_asist>();
        }
    
        public int id_asistencia { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ICollection<det_asist> det_asist { get; set; }
    }
}
