//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class confirmacion
    {
        public confirmacion()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public int id_confirmacion { get; set; }
        public System.DateTime fecha { get; set; }
        public System.Guid guid { get; set; }
        public bool habilitado { get; set; }
        public int tipo { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
