//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_acciones
    {
        public int id_acciones { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
        public string nombre_ejecucion { get; set; }
        public int id_ejecutor { get; set; }
    }
}
